apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-web-app
  labels:
    app: my-first-web-app-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-web-app-label
  template:
    metadata:
      labels:
        app: my-first-web-app-label
    spec:
      containers:
      - name: mvc-app
        image: docker.io/rkb0124/myfirstwebappimage:testing
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "400Mi"
          requests:
            memory: "200Mi"
