apiVersion: v1
kind: Service
metadata:
  name: my-first-web-app-service
spec:
  type: NodePort
  selector:
    app: my-first-web-app-label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007